# Generated by Django 4.2.5 on 2023-09-25 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='chat_icon',
            field=models.ImageField(blank=True, null=True, upload_to='chat_images'),
        ),
    ]
