# Generated by Django 4.2.5 on 2023-09-25 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='team_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='user_profile.team'),
        ),
    ]
