# Generated by Django 4.2.5 on 2024-01-20 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_user_exp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='team_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_profile.team'),
        ),
    ]
