# Generated by Django 4.2.5 on 2024-01-19 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_user_exp'),
        ('progress', '0002_userachievement_date_alter_userachievement_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='team_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='user_profile.team'),
        ),
    ]
